site_name: Algoritmos e Programação de Computadores
site_author: Guilherme N. Ramos
copyright: <p><a href="https://gnramos.github.com/APC">Livro de APC</a> por <a href="https://gnramos.github.io">Guilherme N. Ramos</a> <a href="https://github.com/gnramos/APC/blob/main/LICENSE" target="_blank" style="display:inline-block;"><img style="height:20px!important;margin-left:3px;display:inline-block;vertical-align:middle;" src="https://img.shields.io/badge/license-MIT-green"></a></p>
docs_dir: docs
site_dir: html
# repo_url: https://github.com/gnramos/APC
theme:
    name: material
    features:
        - content.code.copy
        - content.tabs.link
        - navigation.instant
        - navigation.footer
        - search.highlight
        - search.suggest
        - toc.integrate
    language: pt
    logo: assets/img/unb.png
    favicon: assets/img/unb.ico
extra:
    generator: false
    mailto: gnramos@unb.br
extra_css:
    - assets/stylesheets/extra.css
extra_javascript:
    - assets/javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
hooks:
    - hooks.py
markdown_extensions:
    - admonition
    - attr_list
    - md_in_html
    - footnotes
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.details
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets:
        base_path: docs/assets/src
        check_paths: true
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
        alternate_style: true
nav:
    - Início: index.md
    - Pensamento Computacional: pensamento_computacional.md
    - Computadores: computadores.md
    - Algoritmos: algoritmos.md
    - Programação: programacao.md
    - Tipos de Dados: programacao/tipos_de_dados.md
    - Fluxo de Controle: programacao/fluxo_de_controle.md
    - Recursão: programacao/funcoes_recursivas.md
plugins:
    - search
    - markdown-exec
    - bibtex:
        bib_file: bibliografia.bib
